export interface FlightProfile{
    accSectors?:string;
    arrival?:string;
    callsign:string;
    departure?:string;
    deptTma?:string;
    destTma?:string;
    directDistance?:number;
    endRadian?:number
    firstEnrDistance?:number;
    firstEnrTime?:number;
    firstEntLevel?:number;
    firstEntTime?:string;
    firstEntX?:number;
    firstEntY?:number;
    firstExitLevel?:number;
    firstExitTime?:string;
    firstExitX?:number;
    firstExitY?:number;
    firstLevel?:number;
    firstTime?:string;
    firstX?:number;
    firstY?:number;
    flightType?:number;
    id:number;
    lastLevel?:number;
    lastTime?:string;
    lastX?:number;
    lastY?:number;
    secondEnrDistance?:number;
    secondEnrTime?:number;
    secondEntLevel?:number;
    secondEntTime?:string;
    secondEntX?:number;
    secondEntY?:number;
    squawk:string;
    startRadian?:number;
}